[tool.poetry]
name = "mercure"
# Don't change the version. Version will be managed by CI via dist-make target.
version = "0.0.1"
description = "The service to push events between parties. The messenger of gods."
authors = ["BCD TripTech <development@bcdtriptech.com>"]
license = "BSD License"

[tool.poetry.dependencies]
python = "^3.7"

aiohttp = { version = "^3.4.4", optional = true }
requests = { version = "^2.21", optional = true }
gevent = { version = "^1.4.0", optional = true }

[tool.poetry.dev-dependencies]
coverage = "^4.5"
flake8 = "^3.7"
pytest = "^4.5"
flake8-sorted-keys = "^0.2.0"
flake8-import-order = "^0.18.0"
flake8-comprehensions = "^2.0"
flake8-quotes = "^2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.extras]
common = ["requests"]
gevent = ["requests", "gevent"]
async = ["aiohttp"]
