[tool.poetry]
name = "jsonschema-to-openapi"
version = "0.1.0"
description = "Converts a JSON schema to an OpenAPI specification version 3.0."
authors = [
    "Instaffo GmbH <info@instaffo.de>",
    "Jan-Benedikt Jagusch <jan@instaffo.de>"
]
readme = "README.md"
repository = "https://gitlab.com/InstaffoOpenSource/DataScience/jsonschema-to-openapi"
homepage = "https://instaffo.com"

[tool.poetry.dependencies]
python = "^3.6"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
black = {version="19.10b0", allow-prereleases=true}
ipykernel = "^5.1"
pylint = "^2.4"
pytest = "^5.3"
tox = "^3.14"
codecov = "^2.0.22"
pytest-cov = "^2.8.1"

[tool.poetry.scripts]
jsonschema-to-openapi = "jsonschema_to_openapi.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
