[tool.poetry]
name = "pyCmdlineHistory"
version = "1.1.3"
description = "Save command line history and provide a command line completer for python."

packages = [
    { include = "berhoel" },
]

authors = ["Sunjoong LEE <sunjoong@gmail.com>",
        "Berthold HÃ¶llmann <berthold@xn--hllmanns-n4a.de>"]
license = "CC-BY-SA-4.0"

repository = "https://gitlab.com/berhoel/python/pyCmdlineHistory.git"

readme = "README.md"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX",
    "Topic :: System :: Shells",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^2.7 || >3.5"

pathlib2 = [
    {version="^2.3.5", python="^2.7"}
]

[tool.poetry.dev-dependencies]
tox = "^3.14.5"
pytest = [
    {version="^5.3.5", python=">3.5"},
    {version="^4.6", python="^2.7"}
]
pdoc3 = [
    {version="^0.7.5", python="^3.5"}
]
pytest-sugar = [{version="^0.9.2", python="^2.7"}]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
