[tool.poetry]
name = "pgformatter"
version = "0.1.2"
description = "Thin Python wrapper for pgFormatter. Compatible with AWS Lambda or any environment with Perl."
authors = ["Nathan Cahill <nathan@nathancahill.com>"]
include = ["bin/**/*"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
