[tool.poetry]
name = "ios-fw"
version = "0.1.4"
description = "IOS firmware utilities"
authors = ["Charlie Brown <whysoyum@gmail.com>"]
packages = [
    { include = "packers/*.py" },
    { include = "cli.py" },
]

[tool.poetry.dependencies]
python = "^3.6"
construct = "^2.10.56"
click = "^7.1.1"
coloredlogs = "^14.0"
simpleelf = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
ios-fw = 'cli:main'
